export const fumbleNaturalTitle = ["Awkward Attack",
  "Bad Headbutt",
  "Battered",
  "Bleeding Fist",
  "Bone Bruise",
  "Broke A Nail",
  "Broken Tooth",
  "Bruised Ego",
  "Brutal Collision",
  "Caught Your Attack",
  "Don’t Pick At It",
  "Eye Strain",
  "Ferocious Fumble",
  "Fist Meets Face",
  "Frustration",
  "Got Too Close",
  "Great Roar",
  "Hangnail",
  "He Bit Me",
  "He’s Sharp",
  "Head, Meet Wall",
  "Ingrown Nail",
  "Jam A Finger",
  "Muscle Tear",
  "Not The Weak Point",
  "Off Balance",
  "Out Of Position",
  "Overexertion",
  "Overextend",
  "Overthink It",
  "Pinched Nerve",
  "Pins And Needles",
  "Punctured Foot",
  "Smash The Floor",
  "Sneeze!",
  "Sprain",
  "Stinging Failure",
  "Stop Hitting Yourself",
  "That’s Disgusting",
  "Tiring Attack",
  "Torn Muscle",
  "Tripped",
  "Twisted",
  "Unintentional Move",
  "Upset Tummy",
  "We Have A Wiener",
  "Whirlwind Of Shame",
  "Wide Open",
  "Winds Of Change",
  "How In The World?"
];

export const fumbleNaturalText = ["Your attack fails and you suffer a -2 penalty to defense rolls for 1d4 rounds.<br>Save: Dexterity DC 20 negates.<br>Heal: A DC 20 Acrobatics check removes the attack penalties.",
  "Your attack fails and you are stunned for 1 round.<br>Save: Constitution DC 20 negates.",
  "Your attack fails and you suffer a -2 penalty on saves and skill checks for 1d4 hours.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check removes the penalties.",
  "Your attack fails and you take 1d6 points of bleed damage.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check ends the bleed effect.",
  "Your attack fails and you take 1d2 points of Constitution damage.<br>Save: Constitution DC 20 negates.<br>Heal: Rest or restorative magic.",
  "Your attack fails and you take bonus damage and you cannot use this attack until healed.<br>Save: Constitution DC 20 negates.",
  "Your attack fails and you suffer a -2 penalty on attack rolls for 1d6 minutes.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check removes the attack penalties.",
  "Your attack fails and you suffer Disadvantage to attack any other target for 1d4 rounds (or until the target is dead).<br>Save: Resolve DC 20 negates.",
  "Your attack fails but deals bonus damage to the original target and you are stunned for 2 rounds.<br>Save: Constitution DC 20 negates (2 saves).<br>Heal: A DC 20 Heal check removes the stunned condition.<br>Special: Each saving throw reduces the duration of this fumble by 1 round.",
  "Your attack fails and the target may attempt to trip, bull rush, or overrun you (target’s choice) as a free action without causing an attack of opportunity.<br>Save: Dexterity DC 20 negates.",
  "Your attack fails and you take 1 point of Constitution damage.<br>Save: Constitution DC 20 negates.<br>Heal: Rest or restorative magic.",
  "Your attack fails and you are blinded for 1 round.<br>Save: Constitution DC 20 negates.",
  "Re-roll the attack targeting the next nearest ally to the original target within reach; it is possible to critically hit yourself or an ally in this manner. If there are no other creatures, you target yourself.<br>Save: Dexterity DC 20 negates.<br>Special: If targeting yourself, you may defend against this attack as normal but may not negate the attack (such as a counter, block, or parry) if it is successful.",
  "The attack hits you instead and is considered a critical threat. Determine the severity of the critical hit as normal.<br>Save: Dexterity DC 20 negates.<br>Special: You do not defend against this attack and may not negate the attack (such as a counter, block, or parry).",
  "Your attack fails and you suffer Disadvantage on all attack rolls until the end of our next turn.<br>Save: Resolve DC 20 negates.",
  "Your attack fails and the target may start a grapple against you as a free action which does not provoke an attack of opportunity.<br>Save: Dexterity DC 20 negates.",
  "Your attack fails and you are deafened until healed.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check removes the deafened condition.",
  "Your attack fails and you cannot use this attack type again for 1d6 rounds.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check removes the attack penalty.",
  "Your attack fails and you provoke an attack of opportunity from the target.<br>Save: Dexterity DC 20 negates.<br>Special: Creatures gain Advantage on their attack of opportunity if it is a Bite natural attack.",
  "Your attack fails and you take bonus damage.<br>Save: Dexterity DC 20 negates.",
  "Your attack fails and you are dazed for 1d3 rounds.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check removes the dazed condition.",
  "Your attack fails and you suffer a -1 penalty on attack rolls until you score a critical hit.<br>Save: Constitution DC 20 negates.<br>Recover: You must succeed at a Constitution save or score a critical hit to end this effect. You may re-roll the save each round.<br>Special: Each attack you miss your target increases the penalty by -1.",
  "Your attack hits and deals damage to yourself, but it is all nonlethal damage.<br>Save: Constitution DC 20 negates.<br>Special: You do not defend against this attack and may not negate the attack (such as a counter, block, or parry).",
  "Your attack fails and you take 1d4 points of Strength damage.<br>Save: Constitution DC 20 negates.<br>Heal: Rest or restorative magic.",
  "Your attack hits and deals damage to your target’s armor, and you suffer half the damage dealt and cannot use that attack for 1d3 rounds.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check removes the penalty. If opponent does not wear armor, deal damage to shield or an item worn.",
  "Your attack fails and you become staggered until the end of your next turn.<br>Save: Dexterity DC 20 negates.<br>Special: If you attempt a move action while staggered this way, you must succeed a DC 20 Acrobatics check or fall prone instead.",
  "Your attack fails and you cannot use this attack until the end of your next turn.<br>Save: Dexterity DC 20 negates.",
  "Your attack fails and you are exhausted.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check will reduce the exhausted condition to fatigued instead.",
  "Your attack fails and you provoke an attack of opportunity from all threatening opponents.<br>Save: Dexterity DC 20 negates.",
  "Your attack fails and you suffer Disadvantage on all attacks against that opponent for 3 rounds.<br>Save: Wisdom DC 20 negates.<br>Recover: A DC 20 Intuition check (as a standard action) removes the attack penalty.",
  "Your attack fails and you reduce your reach by 5 feet for 3 rounds.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check removes the reach penalty.<br>Special: If this reduces your reach to 0, you may not attack.",
  "Your attack fails and you are sickened for 1d6 rounds.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check removes the sickened condition.",
  "Your attack fails and you suffer bonus damage. Your speed is reduced by half until healed.<br>Save: Dexterity DC 20 negates.<br>Heal: Rest or restorative magic.",
  "Your attack fails and you kick up dust that blinds you for 1d4 rounds.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check removes the blindness condition.",
  "Your attack fails and you are dazed until the end of your next turn.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check removes the dazed condition.",
  "Your attack fails and you take 1d4 points of Dexterity damage.<br>Save: Constitution DC 20 negates.<br>Heal: Rest or restorative magic.",
  "Your attack fails and you take 1d6 points of nonlethal damage and a -2 penalty on attack rolls with that attack for 1d4 rounds.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check removes the attack penalties.",
  "The attack hits and deals damage to yourself instead of the target.<br>Save: Dexterity DC 20 negates.<br>Special: You do not defend against this attack and may not negate the attack (such as a counter, block, or parry).",
  "Your attack fails and you are nauseated for 1d6 rounds.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check removes the attack penalties.",
  "Your attack fails and you are fatigued.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check removes the fatigued condition.",
  "Your attack fails and you take 1 point of Strength drain.<br>Save: Constitution DC 20 negates.<br>Heal: Restorative magic is required to heal ability drain.",
  "Your attack fails and you are knocked prone.<br>Save: Dexterity DC 20 negates.<br>Recover: You must expend a standard action to stand from being prone. This provokes attacks of opportunity from all threatening opponents.",
  "Your attack fails and you become entangled in your gear.<br>Save: Dexterity DC 20 negates.<br>Recover: You must spend a standard action to free yourself.",
  "Your attack fails and you move 10 feet in a random direction and provoke attacks of opportunity as normal.<br>Save: Dexterity DC 20 negates.<br>Special: If wearing heavy armor, you suffer disadvantage on your Dexterity save and fall prone on a failed save.",
  "Your attack fails and you are sickened for 1d4 rounds.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check removes the sickened condition.",
  "Your attack fails and you fall unconscious for 1d6 rounds.<br>Save: Resolve DC 20 negates.<br>Heal: A DC 20 Heal check awakens the unconscious character.",
  "Your attack fails and deals bonus damage to yourself and all creatures adjacent to you except the original target.<br>Save: Dexterity DC 20 negates.",
  "Your attack fails and you are flat-footed until the end of your next turn.<br>Save: Dexterity DC 20 negates.",
  "Your attack fails and you threaten no squares for 1d6 rounds.<br>Save: Resolve DC 20 negates.<br>Heal: A DC 20 Intuition check (as a standard action) removes the attack penalties.",
  "The attack hits and deals damage to the original target and the opponent may not negate the attack (such as a counter, block, or parry). This attack may not critically hit or cause any special effects (such as from a Strike maneuver)"
];