export const fumbleMeleeTitle = ["All Or Nothing",
  "Armor Smash",
  "Attack The Darkness",
  "Awkward Attack",
  "Backswing",
  "Bad Grip",
  "Bent",
  "Better To Give",
  "Bohemian Earspoon",
  "Bonk",
  "Broken Blade",
  "Broken Haft",
  "Butterfingers",
  "Catastrophic Failure",
  "Catch Your Breath",
  "Critical Mistake",
  "Cutter",
  "Eat Dirt",
  "Fling",
  "Fog Of War",
  "Funny Bone",
  "Go For The Eyes",
  "Hand It Over",
  "I Told You It Was Sharp",
  "Notched",
  "Off Balance",
  "Overextended",
  "Parry! Dodge! Spin! Thrust!",
  "Pin Prick",
  "Pointy End Goes There",
  "Pulled Muscle",
  "Punt",
  "Second Thoughts",
  "Slipped ",
  "Sorry!",
  "Spinning Swing",
  "Strain",
  "Stuck",
  "Surrounded By Foes",
  "This Is Bad",
  "This Sword Is Heavy",
  "Too Much Stuff",
  "Vibration",
  "Wait! What?",
  "Who Was That?",
  "Wide Open",
  "Winded",
  "Wrong End",
  "You Meant To Do That",
  "How In The World?"
];

export const fumbleMeleeText = [
  `Your attack fails and you suffer a -1 penalty on attack rolls until you score a critical hit.
Save: Resolve DC 20 negates.
Recover: You must succeed at a Resolve save or score a critical hit to end this effect. You may re-roll the save each round.
Special: Each attack you miss your target increases the penalty by -1.`,
  "Your attack hits and deals damage to your armor instead of your target.<br>Save: Dexterity DC 20 negates.<br>Recover: A Craft DC 20 check is needed to repair the damage.<br>Special: If you do not wear armor, damage is dealt to shield or to yourself instead.",
  "Your attack fails and all of your enemies are considered to have concealment from you (20% miss chance) for 1d4 rounds.<br>Save: Resolve DC 20 negates.<br>Recover: You may continue to make a Resolve save each round you are affected to end the duration.",
  "Your attack fails and you take a -2 penalty to defense rolls for 1d4 rounds.<br>Save: Dexterity DC 20 negates.<br>Recover: You must expend a greater action to recover.<br>Special: If using a two-handed weapon, add +1 round to the duration of the penalty.",
  "Re-roll the attack with yourself as the target; it is possible to critically hit yourself in this manner.<br>Save: Dexterity DC 20 negates.<br>Special: You may defend against this attack as normal but may not negate the attack (such as a counter, block, or parry) if it is successful.",
  "Your attack fails and you weapon deals nonlethal damage for the next 3 rounds.<br>Save: Dexterity DC 20 negates.<br>Recover: Expend a standard action to fix your grip and end the nonlethal damage.",
  "Your attack fails and you weapon deals nonlethal damage for the next 3 rounds.<br>Save: Dexterity DC 20 negates.<br>Recover: Expend a standard action to fix your grip and end the nonlethal damage.",
  "Your attack hits and damages you instead. Use your target’s Strength modifier when calculating the damage.<br>Save: Dexterity DC 20 negates.<br>Special: Re-roll attack to determine if you critically hit yourself. This re-roll cannot miss or fumble.",
  "Your attack fails and you are deafened until healed.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check ends the deafened condition.",
  "Your attack fails and you are stunned until the end of your next turn.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check removes the stun effect.<br>Special: If wielding a bludgeoning weapon, you are stunned for 1d4 rounds instead.",
  "Your attack hits and deals damage to your weapon instead of your target.<br>Save: Dexterity DC 20 negates.<br>Recover: A Craft DC 20 check is needed to repair the damage.<br>Special: If you do not wield a weapon, damage is dealt to yourself instead.",
  "Your attack fails and your weapon suffers bonus damage. The weapon suffers a -2 penalty on attack rolls and loses the reach property until repaired.<br>Save: Dexterity DC 20 negates.<br>Recover: A DC 20 Craft Weapons check repairs the weapon.<br>Special: If you are not wielding a reach weapon, your attack hits and deals damage to your weapon instead.",
  "Your attack fails and you drop your weapon.<br>Save: Dexterity DC 20 negates.<br>Recover: You must expend a standard action to pick up your weapon. This provokes an attack of opportunity from threatening foes.<br>Special: If using a light weapon, it is flung 1d6 squares away instead.",
  "Your attack fails and you fall unconscious for 1d6 rounds.<br>Save: Resolve DC 20 negates.<br>Recover: You may make a new saving throw each round.<br>Special: If wielding a bludgeoning weapon, add 2 rounds to the duration.",
  "Your attack fails and you become staggered until the end of your next turn.<br>Save: Constitution DC 20 negates.<br>Special: If wielding a two-handed weapon or wearing heavy armor, add one round to the duration.",
  "The attack hits and deals damage to you instead and is considered a critical threat. Determine the severity of the critical hit as normal.<br>Save: Dexterity DC 20 negates.<br>Special: You do not defend against this attack and may not negate the attack (such as a counter, block, or parry).",
  "Your attack fails and you take 1 point of Strength bleed.<br>Save: Dexterity DC 20 negates.<br>Heal: A DC 20 Heal check ends the Strength bleed. Rest or restorative magic is needed to heal the ability damage.<br>Special: If you are wielding a slashing weapon, this increases the Strength bleed to 2.",
  "Your attack fails and you fall prone and are blinded for 1d3 rounds.<br>Save: Dexterity DC 20 negates.<br>Recover: Expend a standard action to stand up from being prone, and a standard action to wipe the debris from your eyes.",
  "Your attack fails and you throw your weapon where it lands 1d6 squares away in a random direction.<br>Save: Dexterity DC 20 negates.<br>Recover: Expend a standard action to retrieve your weapon after you move to its location.<br>Special: If wielding a light weapon, add +1 square to the distance traveled.",
  "Your attack fails and you threaten no squares for 1d6 rounds.<br>Save: Resolve DC 20 negates.<br>Recover: Expend a greater action to regain your senses and composure.<br>Special: If you are below half hit points, you suffer disadvantage on this saving throw.",
  "Your attack fails and you drop whatever is in your off hand.<br>Save: Dexterity DC 20 negates.<br>Recover: Expend a standard action to retrieve your item.<br>Special: If that item is a light weapon, it is flung 1d6 squares away instead.",
  "Your attack fails and you are blinded until the end of your next turn.<br>Save: Dexterity DC 20<br>Heal: A Heal check DC 20 removes the blinded condition.<br>Special: If you are using a piercing weapon, add 1d3 rounds of blindness.",
  "Your attack fails and your target gains possession of your weapon.<br>Save: Dexterity DC 20 negates.<br>Special: If wielding a two-handed weapon, you gain advantage on your saving throw.",
  "Your attack fails and you suffer 1d6 points of bleed damage.<br>Save: Dexterity DC 20<br>Heal: Curative magic or a DC 20 Heal check heals.<br>Special: If you are using a slashing or piercing weapon, add +2 points of bleed.",
  "Your attack fails and your weapon suffers bonus damage.<br>Save: Dexterity DC 20 negates.<br>Repair: A Craft skill check of DC 20 is required to repair the damage inflicted.<br>Special: If wielding a two-handed weapon, it bonus damage again.",
  "Your attack fails and you suffer disadvantage on all attack rolls until the end of your next turn.<br>Save: Dexterity DC 20 negates.<br>Recover: Expend a greater action to gather your balance and composure.<br>Special: If wielding a two-handed weapon, add one round to the duration.",
  "Your attack fails and you provoke an attack of opportunity from all opponents who threaten you.<br>Save: Dexterity DC 20 negates.",
  "Your attack fails and you are dazed until the end of your next turn.<br>Save: Resolve DC 20 negates.<br>Recover: Expend a greater action to gather your balance and composure.",
  "Your attack fails and you take 1d4 points of Bleed damage.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check ends the bleed effect.<br>Special: If wielding a piercing weapon, add +2 additional points of bleed.",
  "Your attack fails and you take 1 point of Constitution damage.<br>Save: Dexterity DC 20 negates.<br>Heal: Rest or restorative magic.<br>Special: If wielding a piercing weapon, add 1 point of additional Constitution damage.",
  "Your attack fails and you take 1d4 points of Strength damage.<br>Save: Constitution DC 20 negates.<br>Heal: Rest or restorative magic.",
  "Your attack fails and your weapon flies 2d6 squares in a random direction.<br>Save: Dexterity DC 20 negates.<br>Recover: Expend a standard action to retrieve your weapon from its location.<br>Special: If wielding a light weapon, add +1 square to the distance traveled.",
  "Your attack fails and you are sickened for 1d6 rounds.<br>Save: Resolve DC 20 negates.<br>Recover: You may continue to make a save each round to end the effect.<br>Special: If you are shaken or frightened, you suffer disadvantage on your saving throw.",
  "Your attack fails and you are knocked prone.<br>Save: Dexterity DC 20 negates.<br>Recover: Expend a standard action to stand up from prone (this provokes attacks of opportunity from all threatening foes).",
  "Re-roll the attack targeting an ally adjacent to you or the original target; it is possible to critically hit yourself or your ally in this manner. If there are no adjacent allies, you target yourself.<br>Save: Dexterity DC 20 negates.<br>Special: If targeting yourself, you may defend against this attack as normal but may not negate the attack (such as a counter, block, or parry) if it is successful.",
  "Your attack fails and you are sickened for 1d4 rounds.<br>Save: Resolve DC 20 negates.<br>Recover: Expend a greater action to gather your balance and composure.<br>Special: If wielding a two-handed weapon, add +1 round to the duration.",
  "Your attack fails and you take 1d4 points of Dexterity damage.<br>Save: Constitution DC 20 negates.<br>Heal: Rest or restorative magic.<br>Special: If using a light weapon, reduce the Dexterity damage to 1d3.",
  "Your attack fails and your weapon becomes stuck in a nearby surface in your square.<br>Save: Dexterity DC 20 negates.<br>Recover: As a standard action, you must make a successful DC 20 Strength check to retrieve your weapon.",
  "The attack hits and deals damage to an ally within reach instead and is considered a critical threat. Determine the severity of the critical hit as normal.<br>Save: Dexterity DC 20 negates.<br>Special: If there are no allies within reach, the attack hits yourself instead. You do not defend against this attack and may not negate the attack (such as a counter, block, or parry).",
  "Your attack fails and you take bonus damage as bleed damage.<br>Save: Constitution DC 20 negates.<br>Recover: A Heal check DC 20 removes the bleed condition.",
  "Your attack fails and you become fatigued.<br>Save: Constitution DC 20 negates.<br>Recover: A Heal DC 20 check removes the fatigued condition, as does rest.",
  "Your attack fails and you become entangled in your gear.<br>Save: Dexterity DC 20<br>Recover: You must spend a standard action to free yourself.<br>Special: If wielding a prehensile weapon (chain, whip, etc.), you suffer disadvantage on your Dexterity save.",
  "Your attack fails and you strike something solid, suffering 1d3 points of Strength damage, and drop your weapon.<br>Save: Constitution DC 20<br>Heal: Rest or restorative magic.<br>Special: If wielding a prehensile weapon (chain, whip, etc.), the Strength damage drops to 1.",
  "Your attack fails and you become confused for one round.<br>Save: Resolve DC 20 negates. <br>Special: If wielding a bludgeoning weapon, add +1 round to the duration.",
  "Your attack fails and you are grazed by your own weapon becoming dazed for 1d3 rounds.<br>Save: Resolve DC 20<br>Recover: You may make a Resolve save each round to end the effect. A DC 20 Heal check will also remove the effect.<br>Special: If wielding a bludgeoning weapon, add +1 round to the duration.",
  "Your attack fails and you become flat-footed until the end of your next turn.<br>Save: Dexterity DC 20 negates",
  "Your attack fails and you become exhausted.<br>Save: Constitution DC 20 negates.<br>Heal: Expend a greater action to regain your wind, removing the exhausted condition.<br>Special: If wearing heavy armor, you must expend a greater action and make a successful DC 20 Constitution save to remove the exhausted condition.",
  "Your attack fails and you take bonus damage.<br>Save: Constitution DC 20 negates.<br>Heal: A Heal check DC 20 removes the bleed effect.<br>Special: If using a slashing weapon, you take bonus damage again.",
  "Your attack fails and you move 10 feet in a random direction and provoke attacks of opportunity as normal.<br>Save: Dexterity DC 20 negates.<br>Special: If wearing heavy armor, you must suffer disadvantage on your Dexterity save and fall prone on a failed save.",
  "The attack hits and deals damage to the original target and the opponent may not negate the attack (such as a counter, block, or parry). This attack may not critically hit or cause any special effects (such as from a Strike maneuver)"
]