export const fumbleRangedTitle = ["Aching Back",
  "Aim Carefully Next Time",
  "All Thumbs",
  "Amazing Miss",
  "Archer's Elbow",
  "Awkward Attack",
  "Backfire",
  "Bad Alignment",
  "Busted",
  "Bull's Eye",
  "Close To The Ear",
  "Cracked",
  "Don't Hit Me",
  "Double Miss",
  "Errant Aim",
  "Everything You Got",
  "Friendly Fire",
  "Head Rush",
  "Huh?",
  "In The Line Of Fire",
  "Insecure",
  "Klutz",
  "Lost Grip",
  "Lost The Target",
  "Lowered Guard",
  "Misjudged The Distance",
  "Mix It Up",
  "My Spleen!",
  "Nicked",
  "Notched Fingers",
  "Overcompensated",
  "Overshot",
  "Phantom Wind",
  "Pinched In Parts",
  "Recoil",
  "Seeing Double",
  "Shot Your Foot",
  "Snapped Component",
  "So Much Blood",
  "Spilled Ammo",
  "Sprain",
  "Tied Up",
  "Torn Tendon",
  "Umm, Oops",
  "Weapon Jam",
  "What Are The Odds?",
  "Whoops!",
  "Wide Open",
  "Wrong Weapon",
  "How In The World?"
];

export const fumbleRangedText = ["Your attack fails and you become fatigued.<br>Save: Constitution DC 20 negates.<br>Recover: Heal check DC 20 or rest for 8 hours.<br>Special: If wearing heavy armor or wielding a heavy crossbow, you suffer disadvantage to your save.",
  "Your attack fails and for the next 3 rounds, you suffer disadvantage on all ranged attack made without the Aim action.<br>Save: Resolve DC 20 negates.<br>Recover: You may take a greater action to clear your head and make a successful DC 20 Perception check to end the penalty.",
  "Your attack fails and you lose your Dexterity bonus on attack rolls for 3 rounds.<br>Save: Dexterity DC 20 negates.<br>Recover: You must expend a greater action and make a successful DC 20 Acrobatics skill check to regain your Dexterity bonus.",
  "Your attack fails and you are stunned until the end of your next turn.<br>Save: Resolve DC 20 negates.",
  "Your attack fails and you take a -2 penalty on all ranged attack rolls for 1d4 minutes.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check removes the attack roll penalty.",
  "Your attack fails and you take a -2 penalty to defense rolls for 1d4 rounds.<br>Save: Dexterity DC 20 negates.<br>Recover: As a standard action, a successful DC 20 Dexterity save removes the attack roll penalty.",
  "Re-roll the attack with yourself as the target; it is possible to critically hit yourself in this manner.<br>Save: Dexterity DC 20 negates.<br>Special: You may defend against this attack as normal but may not negate the attack (such as a counter, block, or parry) if it is successful.",
  "Your attack fails and you suffer disadvantage on all attacks with this weapon until repaired.<br>Save: Dexterity DC 20 negates.<br>Repair: A DC 20 Craft Weapon check removes the attack penalty.",
  "Your attack fails and your attack deals damage to your weapon instead of your target.<br>Save: Dexterity DC 20 negates.<br>Recover: A Craft DC 20 check is needed to repair the damage.<br>Special: If you do not wield a weapon, damage is dealt to yourself instead.",
  "Your attack fails and your shot ricochets near the eye. You take bonus damage and are blinded until the end of your next turn.<br>Save: Dexterity DC 20 negates.<br>Heal: A DC 20 Heal check will remove the blinded condition.",
  "Your attack fails and you are deafened until healed.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check removes the deafened condition.<br>Special: If using a firearm, the DC increases to 25.",
  "Your attack fails and your weapon takes bonus damage.<br>Save: Dexterity DC 20 negates.<br>Repair: A DC 20 Craft Weapon check will repair the damage.<br>Special: If you do not wield a weapon, bonus damage is dealt to yourself instead.",
  "Your attack fails and you take an additional -2 penalty on ranged attacks for each ally in melee combat with your target for 3 rounds.<br>Save: Resolve DC 20 negates.<br>Recover: Spend a standard action to make a Perception check DC 20 to removes the attack penalty.",
  "Your attack fails and you spend twice as much ammunition on this attack.<br>Save: Dexterity DC 20 negates.",
  "Re-roll the attack targeting the next nearest creature to the original target; it is possible to critically hit yourself or an ally in this manner. If there are no other creatures, you target yourself.<br>Save: Dexterity DC 20 negates.<br>Special: If targeting yourself, you may defend against this attack as normal but may not negate the attack (such as a counter, block, or parry) if it is successful.",
  "Your attack fails and you become exhausted.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check or rest removes the exhaustion.",
  "Re-roll the attack targeting the next nearest ally to the original target; it is possible to critically hit yourself or an ally in this manner. If there are no other creatures, you target yourself.<br>Save: Dexterity DC 20 negates.<br>Special: If targeting yourself, you may defend against this attack as normal but may not negate the attack (such as a counter, block, or parry) if it is successful.",
  "Your attack fails and you become sickened for 1d4 rounds.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check or rest removes the sickened condition.",
  "Your attack fails and you are confused until the end of your next turn.<br>Save: Resolve DC 20 negates.",
  "The attack hits and deals damage to an ally closest to the target instead and is considered a critical threat. Determine the severity of the critical hit as normal.<br>Save: Dexterity DC 20 negates.<br>Special: If there are no allies within reach, the attack hits yourself instead. You do not defend against this attack and may not negate the attack (such as a counter, block, or parry).",
  "Your attack fails and you suffer a -1 penalty on attack rolls until you score a critical hit.<br>Save: Resolve DC 20 negates.<br>Recover: You must succeed at a Resolve save or score a critical hit to end this effect. You may re-roll the save each round.<br>Special: Each attack you miss your target increases the penalty by -1.",
  "Your attack fails and you drop your weapon in your square.<br>Save: Reflex 20 negates.<br>Recover: You must expend a standard action to pick it up. This provokes attacks of opportunity from all threatening foes.",
  "Your attack fails and you become staggered until the end of your next turn.<br>Save: Dexterity DC 20 negates.",
  "Your attack fails and you suffer disadvantage on all attack rolls until the end of your next turn.<br>Save: Resolve DC 20 negates.",
  "Your attack fails and you provoke attacks of opportunity from all threatening foes.<br>Save: Dexterity DC 20 negates.<br>Special: If no foes threaten you this round, you instead suffer a -2 penalty to your defense rolls for 3 rounds.",
  "Your attack fails and all attack rolls beyond the first range increment have triple the normal distance penalty for 3 rounds.<br>Save: Intelligence DC 20 negates.<br>Recover: As a standard action, if you successfully make a Perception DC 20 check, you end the penalty.",
  "Your attack fails and you are unable to make ranged attacks for the next 1d6 rounds.<br>Save: Resolve DC 20 negates.<br>Recover: You must take a greater action to gather your wits and end this effect.",
  "Your attack fails and you take 1 point of Constitution damage.<br>Save: Constitution DC 20 negates.<br>Heal: Rest or restorative magic.",
  "Your attack fails and you take 1d6 points of bleed damage.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check ends the bleed effect.",
  "Your attack fails and you take 1d4 points of bleed and suffer a -2 penalty to ranged attacks while bleeding.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check ends the bleed effect.",
  "Your attack fails and all targets with cover gain advantage to defense rolls against you for 3 rounds.<br>Save: Wisdom DC 20 negates.<br>Recover: As a standard action, make a successful DC 20 Perception check to overcome their additional cover bonus.",
  "Your attack fails and you weapon travels 1d4 times its range increment past the target.<br>Save: Dexterity DC 20 negates.<br>Special: If not using a thrown weapon, it instead slips out of your hand landing 1d6 squares in a random direction.<br>Recover: A standard action is required to pick up a weapon in combat, which provokes attacks of opportunity.",
  "Your attack fails and you compensate for a breeze which isn’t there. You take a -2 penalty on ranged attack rolls for 3 rounds.<br>Save: Wisdom DC 20 negates.<br>Recover: As a standard action, make a successful DC 20 Survival check to end the attack penalty.",
  "Your attack fails and you take 1d2 points of Dexterity damage <br>Save: Dexterity DC 20 negates.<br>Heal: Rest or restorative magic.",
  "Your attack fails and you move backward 1 square and fall prone.<br>Save: Constitution DC 20 negates.<br>Recover: You must expend a standard action to stand up from a prone position. This provokes attacks of opportunity from all threatening foes.",
  "Your attack fails and all your attacks have a 50% miss chance until the end of your next turn.<br>Save: Resolve DC 20 negates.<br>Recover: As a standard action, make a successful DC 20 Perception check to end the miss chance.",
  "Your attack fails and you suffer bonus damage. Your speed is reduced by half until healed.<br>Save: Dexterity DC 20 negates.<br>Heal: Rest or restorative magic.",
  "Your attack fails and a minor part of your weapon jams or breaks and requires 1d3 rounds to fix.<br>Save: Dexterity DC 20 negates.<br>Recover: A successful Craft Weapon DC 20 check is required to repair.",
  "Your attack fails and you are sickened for 1d6 rounds.<br>Save: Resolve DC 20 negates.<br>Heal: A successful Heal DC 20 check removes the sickened condition.",
  "Your attack fails and your ammunition falls from its weapon or container and takes 1d6 rounds to gather up.<br>Save: Dexterity DC 20 negates.<br>Recover: Expend 1d6 rounds gathering the ammo, or switch to another weapon or ammo container if possible.",
  "Your attack fails and you take 1d4 points of Dexterity damage.<br>Save: Constitution DC 20 negates.<br>Heal: Rest or restorative magic.",
  "Your attack fails and you become entangled in your gear.<br>Save: Dexterity DC 20 negates.<br>Recover: You must spend a standard action to free yourself.",
  "Your attack fails and you take 1 point of Dexterity bleed.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check ends the bleed effect. Rest or restorative magic is needed to heal ability damage.",
  "Re-roll the attack with yourself as the target; it is possible to critically hit yourself in this manner.<br>Save: Dexterity DC 20 negates.<br>Special: You may defend against this attack as normal but may not negate the attack (such as a counter, block, or parry) if it is successful.",
  "Your attack fails and your weapon suffers bonus damage. If using a projectile weapon it ceases to function until repaired.<br>Save: Dexterity DC 20 negates.<br>Recover: A Craft DC 20 check is needed to repair the damage.<br>Special: If you do not wield a weapon, damage is dealt to yourself instead.",
  "Re-roll the attack targeting the next nearest creature to the original target; it is possible to critically hit yourself or an ally in this manner. If there are no other creatures, you target yourself.<br>Save: Dexterity DC 20 negates.<br>Special: If you made a thrown attack, you hit the original target, but the weapon ends up in the target’s possession. If targeting yourself, you may defend against this attack as normal but may not negate the attack (such as a counter, block, or parry) if it is successful.",
  "Your attack fails and you are knocked prone.<br>Save: Dexterity DC 20 negates.<br>Recover: You must expend a standard action to stand from prone. This provokes attacks of opportunity from all threatening opponents.",
  "Your attack fails and you are flat-footed until the end of your next turn.<br>Save: Dexterity DC 20 negates.",
  "Your attack fails and you grab a random object from your gear instead of your intended weapon or ammunition.<br>Save: Resolve DC 20 negates.<br>Recover: Expend a standard action to retrieve the correct item.",
  "The attack hits and deals damage to the original target and the opponent may not negate the attack (such as a counter, block, or parry). This attack may not critically hit or cause any special effects (such as from a Strike maneuver)"
];