export const fumbleMagicTitle = ["Cursed",
  "Weak-Minded Fool",
  "Power Transfer",
  "Mental Slip",
  "Not Me, You Fool!",
  "Cold Snap",
  "Jumbled Components",
  "Left Reeling",
  "Fragmented Magic",
  "Blastoff",
  "Caster's Block",
  "Unexpected Blast",
  "Weakened",
  "Backblast",
  "Spell Shield",
  "Bleeding Eyes",
  "Power Down",
  "Energy Transfer",
  "Mind Drain",
  "Nose Bleed",
  "Magic Fatigue",
  "Tiring Spell",
  "Reflection",
  "Power Drain",
  "Electrical Feedback",
  "Acidic Backlash",
  "Poor Trade",
  "Glimpse Of Terror",
  "This Is Hard",
  "Side Effect",
  "Why Me",
  "How Did This Happen?",
  "Vertigo",
  "Monster Rift",
  "Arcane Fire",
  "Can You Hear Me Now?",
  "Now I See You...",
  "You Made Him Bigger",
  "The Magic Is Slipping",
  "Magical Vacuum",
  "Tangled",
  "You Made Him Tougher",
  "Magical Smackdown",
  "Hit By The Ugly Stick",
  "You Made Him Stronger",
  "You Made Him Faster",
  "Distance Rift",
  "Klaatu Barada Necktie",
  "It's Sparkly",
  "Wild Magic"
];

export const fumbleMagicText = ["Your spell fails and you suffer a -4 penalty on attack rolls, saves, skill checks, and ability checks. <br>Save: Resolve DC 20 negates.<br>Heal: This effect can only be cured with remove curse.",
  "Your spell fails and you suffer 1 point of Wisdom bleed damage.<br>Save: Resolve DC 20 negates.<br>Special: The type of magic determines what type of skill check is needed to heal this effect. Arcana for Arcane, Religion for Divine, and Nature for Primal magic.<br>Heal: A DC 20 Skill check ends the ability bleed, but rest or restorative magic is needed to heal ability damage.",
  "Your spell fails and the highest level spell effect on you is transferred to your target for the remainder of its duration.<br>Save: Charisma DC 20 negates.<br>Special: If you have no spell effect on you, you suffer bonus damage instead.",
  "Your spell fails and you suffer Disadvantage on all spell casting rolls until the end of your next turn.<br>Save: Intelligence DC 20 negates.",
  "Your spell succeeds but targets your ally closest to the target instead.<br>Save: Resolve DC 20 negates.<br>Special: If there is no ally within the spell's range, you target yourself instead.",
  "Your spell fails and you suffer bonus damage as cold damage.<br>Save: Resolve DC 20 negates.<br>Special: If the spell would have dealt cold damage, DC 20 Constitution save or you suffer 1d4 Dexterity damage.<br>Heal: Rest or restorative magic is needed to heal ability damage.",
  "Your spell fails and you are staggered until the end of your next turn.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check negates the staggered condition.",
  "Your spell fails and you are stunned for 1 round<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check negates the stunned condition.",
  "Your spell fails and 1d4+2 mirror images of your target spring up around the target as the spell mirror image. These images last for 1 minute or until destroyed.<br>Save: Intelligence DC 20 negates.",
  "Your spell fails and you are thrown 1d6*10 feet in a random direction<br>Save: Resolve DC 20 negates.",
  "Your spell fails and you cannot cast this spell again for 24 hours.<br>Save: Wisdom DC 20 negates.<br>Special: The type of magic determines what type of skill check is needed to heal this effect. Arcana for Arcane, Religion for Divine, and Nature for Primal magic.<br>Heal: A DC 20 Skill check restores your ability to cast this spell.",
  "Your spell succeeds but you suffer bonus damage and the spell affects all other creatures within 30 ft of you.<br>Save: Resolve DC 20 negates.",
  "Your spell fails and the DC to resist your spells and abilities are reduced by 2.<br>Save: Constitution DC 20 negates.<br>Special: The type of magic determines what type of skill check is needed to heal this effect. Arcana for Arcane, Religion for Divine, and Nature for Primal magic.<br>Heal: A DC 20 Skill check negates the penalty.",
  "Your spell succeeds but targets you instead and is considered a critical threat. Determine the severity of the critical hit as normal.<br>Save: Resolve DC 20 negates.<br>Special: You do not defend against this attack (if you have SR) and may not negate the spell (such as a counter spell).",
  "Your spell fails and the target gains SR equal to your proficiency bonus + their Resolve modifier for 1d6 rounds.<br>Save: Resolve DC 20 negates.",
  "Your spell fails and you suffer 1d6 points of bleed damage. You are considered blinded while bleeding.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check negates the bleed.",
  "Your spell fails and you suffer 1 point of Intelligence bleed.<br>Save: Resolve DC 20 negates.<br>Special: The type of magic determines what type of skill check is needed to heal this effect. Arcana for Arcane, Religion for Divine, and Nature for Primal magic.<br>Heal: A DC 20 Skill check ends the ability bleed, but rest or restorative magic is needed to heal ability damage.",
  "Your spell fails and you transfer the knowledge of that spell to the nearest opponent until the end of their next turn. That opponent may invoke the spell on their turn as if it were a spell-like ability.<br>Save: Resolve DC 20 negates.",
  "You suffer 1d4 points of ability damage to Int, Wis, Res, or Charisma determined randomly.<br>Save: Resolve DC 20 negates.<br><br>D4 - Ability Type Damage<br>1 - Int<br>2 - Wis<br>3 - Res<br>4 - Cha<br><br>Heal: Rest or restorative magic is needed to heal ability damage.",
  "Your spell fails and you suffer a number of bleed damage equal to 1/2 bonus damage.<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check negates the bleed.",
  "Your spell fails and you become fatigued. Additionally you cannot cast any spells for 1 round.<br>Save: Constitution DC 20 negates.<br>Heal: Rest or a DC 20 Heal check negates the fatigued condition.",
  "Your spell succeeds but you become Exhausted<br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check Reduces the exhausted condition to fatigued.",
  "Re-roll the spell cast with yourself as the target; it is possible to critically cast upon yourself in this manner.<br>Save: Resolve DC 20 negates.<br>Special: You may defend against this attack as normal but may not negate the attack (such as a counter spell) if it is successful.",
  "Your spell fails and you the cool down time of the spell is increased by 2 rounds.<br>Save: Resolve DC 20 negates.<br>Special: The type of magic determines what type of skill check is needed to heal this effect. Arcana for Arcane, Religion for Divine, and Nature for Primal magic.<br>Heal: A DC 20 Skill check reduces the increased cool down time by 1 round.",
  "Your spell fails and you suffer bonus damage as electricity damage.<br>Save: Resolve DC 20 negates.<br>Special: If the spell would have dealt electricity damage, DC 20 Constitution save or become stunned for 1 round.",
  "Your spell fails and you suffer bonus damage as acid damage.<br>Save: Resolve DC 20 negates.<br>Special: If the spell would have dealt acid damage, DC 20 Dexterity save or bonus damage is also dealt to your armor. If you wear no armor it is dealt to shield or deal additional bonus damage again to yourself.",
  "Your spell succeeds but you must spend double the spell's mana cost. <br>Save: Resolve DC 20 negates.<br>Special: If you do not have enough mana for the spell, your mana is reduced to 0 and you suffer bonus damage.",
  "Your spell fails and you are shaken for 2d4 rounds<br>Save: Resolve DC 20 negates.",
  "Your spell fails and you suffer 1 point of con damage<br>Save: Resolve DC 20 negates.<br>Heal: Rest or restorative magic is needed to heal ability damage.",
  "Your spell fails and one of your items gains a random drawback as per a cursed object.<br>Save: Resolve DC 20 negates.<br>Heal: This effect can only be cured with remove curse.",
  "Your spell fails and you provoke an attack of opportunity from all threatening foes.<br>Save: Resolve DC 20 negates.",
  "Your spell fails and a stinking cloud appears centered on you as per the stinking cloud spell.<br>Save: Resolve DC 20 negates.",
  "Your spell fails and you become nauseated for 1d4 rounds<br>Save: Resolve DC 20 negates.<br>Heal: A DC 20 Heal check Reduces the nauseated condition to sickened.",
  "Your spell fails and is converted into a summon monster spell of the same spell level. The monster(s) summoned are determined at random and are hostile to you.<br>Save: Resolve DC 20 negates.",
  "Your spell fails and you suffer bonus damage as fire damage.<br>Save: Resolve DC 20 negates.<br>Special: If the spell would have dealt fire damage, DC 20 Resolve save or catch fire dealing bonus damage again at the beginning of your turn each round for 1d4 rounds.",
  "Your spell fails and you are deafened. <br>Save: Constitution DC 20 negates.<br>Heal: A DC 20 Heal check negates the deafened",
  "Your spell fails and a target opponent within the spell's range becomes invisible for 1d4 rounds<br>Save: Resolve DC 20 negates.<br>Special: If there are no opponents within the spell's range, you become blind for 1d4 rounds instead.",
  "Your spell fails and a target opponent within the spell's range is enlarged, increasing its size by one size category for 1d4 rounds.<br>Save: Resolve DC 20 negates.<br>Special: If there are no opponents within the spell's range, your size is reduced by one size category for 1d4 rounds instead.",
  "Your spell fails and you suffer a -1 penalty on spell casting rolls until you score a critical hit<br>Save: Resolve DC 20 negates.<br>Recover: You must succeed at a Resolve save or score a critical hit to end this effect. You may re-roll the save each round.<br>Special: Each spell cast you fail increases the penalty by -1.",
  "Your spell fails and 1d4 spell effects active on you are dispelled (Determined randomly)<br>Save: Resolve DC 20 negates.<br>Special: If you have no spell effects that can be dispelled, you suffer bonus damage instead.",
  "Your spell fails and you become entangled in your gear.<br>Save: Dexterity DC 20 negates.<br>Recover: You must spend a standard action to free yourself.",
  "Your spell fails and a target opponent within the spell's range gains 5 Natural Armor for 1d4 rounds.<br>Save: Resolve DC 20 negates.<br>Special: If there are no opponents within the spell's range, you suffer bonus damage instead.",
  "Your spell fails and you suffer Disadvantage on all saving throws for 1d4 rounds.<br>Save: Resolve DC 20 negates.<br>Special: The type of magic determines what type of skill check is needed to heal this effect. Arcana for Arcane, Religion for Divine, and Nature for Primal magic.<br>Heal: A DC 20 Skill check negates this effect.",
  "Your spell fails and you suffer 1 point of Charisma bleed damage<br>Save: Resolve DC 20 negates.<br>Heal: A DC 20 Heal check ends the ability bleed, but rest or restorative magic is needed to heal ability damage.",
  "Your spell fails and a target opponent within the spell's range gains a +8 enhancement bonus to Strength for 1d4 rounds.<br>Save: Resolve DC 20 negates.<br>Special: If there are no opponents within the spell's range, you suffer a -8 enhancement penalty to Strength for 1d4 rounds instead (to a minimum of 1 Strength).",
  "Your spell fails and a target opponent within the spell's range gains the spell haste for 1d4 rounds.<br>Save: Resolve DC 20 negates.<br>Special: If there are no opponents within the spell's range, you suffer the spell slow for 1d4 rounds instead",
  "Your spell fails and you are teleported to the nearest square adjacent to the target of the spell.<br>Save: Resolve DC 20 negates.",
  "Your spell succeeds but targets the nearest ally instead and is considered a critical threat. Determine the severity of the critical hit as normal.<br>Save: Resolve DC 20 negates.<br>Special: If there is no ally, you target yourself instead. If you target yourself, you do not defend against this attack (if you have SR) and may not negate the spell (such as a counter spell).",
  "Your spell fails and all creatures within 30 feet including yourself are blinded for 1 round.<br>Save: Resolve DC 20 negates.",
  "Re-roll your spell cast roll but you gain a +9 critical range and critical fumble range for the spell cast. (Critical Threat 11-20, Critical Fumble 1-10)"
];